# Setup

## Option 1: Anaconda 

This is the most reproducible method of creating a scipy environment across platforms. We could use docker, but then we’d run into issues if we’d like to use gpu optimized libraries. 

1. Install anaconda navigator: https://www.anaconda.com/download/
2. Open the navigator and create a new environment called DLB2017. 
3. Open a terminal from anaconda navigator and install the scipy stack:
```
conda install -c anaconda scipy
```
4. Select DLB2017 as your active environment in the navigator window. 
5. Select home and launch the jupyter conda application listed. 

## Option 2: Raw Install 

Todo

# Numpy Basics
Sources:
* https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
* https://docs.scipy.org/doc/scipy/reference/tutorial/index.html

In [3]:
import numpy as np

In [17]:
a = np.arange(15).reshape(3, 5)
print("Example Matrix - {0}".format(type(a)))
print(a)

Example Matrix - <class 'numpy.ndarray'>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [14]:
print("Shape of matrix: {0}".format(a.shape))
print("Nuber of dimensions: {0}".format(a.ndim))
print("Datatype: {0}".format(a.dtype.name))
print("Total elements: {0}".format(a.size))

Shape of matrix: (3, 5)
Nuber of dimensions: 2
Datatype: int32
Total elements: 15


In [31]:
np.zeros(3)
np.zeros((3,3))
np.zeros((3,3,3))
np.ones( (2,3), dtype=np.int16 )   

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [23]:
b = np.array([(1.5,2,3), (4,5,6)])
print(b)

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]


In [26]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [29]:
print(c)

[[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]


In [35]:
r = np.random.random((2,3))
print(r)

[[ 0.16472788  0.3305694   0.04881993]
 [ 0.13366095  0.93856918  0.58558425]]


In [36]:
r_reshape = r.reshape(3,2)
print(r_reshape)

[[ 0.16472788  0.3305694 ]
 [ 0.04881993  0.13366095]
 [ 0.93856918  0.58558425]]


## Ranges

In [44]:
print(np.linspace( 0, 2, 9 ))
print(np.arange(10, 30, 5 ))

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]
[10 15 20 25]


## Indexing, Slicing, and Iterating

In [46]:
print(r)
print("Row 2: {0}".format(r[1,:]))
print("Column 2: {0}".format(r[:,1]))

[[ 0.16472788  0.3305694   0.04881993]
 [ 0.13366095  0.93856918  0.58558425]]
Row 2: [ 0.13366095  0.93856918  0.58558425]
Column 2: [ 0.3305694   0.93856918]


For more linear algebra operations see: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html